### PR TITLE
Use polyraf for browser compatability

### PR DESCRIPTION
**Pull request by arj03**
I noticed that this module didn't work properly in chrome and that you made a [nice](https://www.npmjs.com/package/polyraf) module to abstract over the different random access files.

PS: can you push polyraf to github? It seems to be missing

Thanks

### CODE REVIEW

**Comment by dominictarr** [comment]
oh yeah, I made that after I started on this

**Comment by dominictarr** [comment]
merged, and pushed https://github.com/dominictarr/polyraf

**Comment by arj03** [comment]
Sweet, thanks! :)

**Comment by arj03** [comment]
@dominictarr can you npm publish as well? ~:)~

**Comment by dominictarr** [comment]
? it looks like it is published? added you as npm owner so you publish too

**Comment by arj03** [comment]
Hmm [npm](https://www.npmjs.com/package/flumelog-aligned-offset). I tried pushing the package but it seems like my user is not able.

**Comment by dominictarr** [comment]
ah, i got confused and added you to polyraf instead, but then I realized you wanted me to publish this module. everything should be good now (also correctly added you to this)

**Comment by arj03** [comment]
Great thanks, I can see how that was a bit confusing :-)

**Pull request merged**
